#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit 1
fi

if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi

./build/bin/bin2ppm < karman.bin > ppms/$1.ppm

echo "Saved as $1.ppm"